version: '3.8'

services:
  react-app:
    container_name: react-app
    image: oven/bun:1.1.3
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173
    tty: true
