name: 'Eslint'
on: pull_request
jobs:
  format_checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3
      - name: Install Deps
        run: bun install
      - name: Run ESLint
        run: bun --bun run lint
